name: 'Deploy'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rsync
        uses: burnett01/rsync-deployments@5.0
        with:
          switches: -avzr --delete --exclude=".git/"
          remote_path: ~/nginx-proxy/
          remote_host: ${{ secrets.HOST }}
          remote_port: ${{ secrets.PORT }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}

      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/nginx-proxy/
            docker compose up -d